#############################################################################
# Makefile for building: qmlPractice
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  qmlPractice.pro
# Template: app
# Command: /home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile qmlPractice.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/5.5.1 -I../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/5.5.1/QtQuick -I../../../Tools/Qt5.5.1/5.5/gcc_64/include -I../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick -I../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui -I../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/5.5.1 -I../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/5.5.1/QtQml -I../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml -I../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtNetwork -I../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore -I. -I../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qmlPractice1.0.0
DISTDIR = /home/uidq6356/workspace/practice/chess/.tmp/qmlPractice1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64 -Wl,-rpath,/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/lib -lQt5Quick -L/usr/lib64 -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		square.cpp qrc_qml.cpp \
		moc_square.cpp
OBJECTS       = main.o \
		square.o \
		qrc_qml.o \
		moc_square.o
DIST          = MyButton.qml \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/unix.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/linux.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/sanitize.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/g++-base.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/qconfig.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt_config.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/spec_post.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/default_pre.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/default_post.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/c++11.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/warn_on.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/resources.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/moc.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/exceptions.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/yacc.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/lex.prf \
		qmlPractice.pro square.h main.cpp \
		square.cpp
QMAKE_TARGET  = qmlPractice
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = qmlPractice


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qmlPractice.pro ../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/unix.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/linux.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/sanitize.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/g++-base.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/qconfig.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt_config.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/spec_post.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/default_pre.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/default_post.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/c++11.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/warn_on.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/resources.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/moc.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/exceptions.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/yacc.prf \
		../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/lex.prf \
		qmlPractice.pro \
		qml.qrc \
		/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/lib/libQt5Quick.prl \
		/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/lib/libQt5Gui.prl \
		/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/lib/libQt5Qml.prl \
		/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/lib/libQt5Network.prl \
		/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile qmlPractice.pro
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/spec_pre.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/unix.conf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/linux.conf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/sanitize.conf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/gcc-base.conf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/g++-base.conf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/common/g++-unix.conf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/qconfig.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt_functions.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt_config.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/spec_post.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/default_pre.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/resolve_config.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/default_post.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/c++11.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/qml_debug.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/warn_on.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/resources.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/moc.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/unix/opengl.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/unix/thread.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/exceptions.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/yacc.prf:
../../../Tools/Qt5.5.1/5.5/gcc_64/mkspecs/features/lex.prf:
qmlPractice.pro:
qml.qrc:
/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/lib/libQt5Quick.prl:
/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/lib/libQt5Gui.prl:
/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/lib/libQt5Qml.prl:
/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/lib/libQt5Network.prl:
/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile qmlPractice.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents square.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp square.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		MyButton.qml \
		main.qml
	/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_square.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_square.cpp
moc_square.cpp: ../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/5.5.1/QtQuick/private/qquickrectangle_p.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/qquickitem.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/qtquickglobal.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qglobal.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qconfig.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qlogging.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qflags.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmutex.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqml.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlprivate.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qtqmlglobal.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qvariant.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qstring.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qchar.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qlist.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qiterator.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qregexp.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qisenum.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmap.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qpair.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qdebug.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qhash.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qobject.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qlocale.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qvector.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qpoint.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qset.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qurl.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlparserstatus.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmllist.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmetaobject.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlcomponent.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlerror.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qjsvalue.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/QObject \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/QList \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qevent.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qregion.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qrect.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmargins.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsize.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qfile.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qfont.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qaccessible.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qeventloop.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qcolor.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qrgb.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qbrush.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qmatrix.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpolygon.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qline.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qtransform.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpainterpath.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qimage.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpixelformat.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpixmap.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/5.5.1/QtQuick/private/qtquickglobal_p.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qloggingcategory.h \
		square.h
	/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/bin/moc $(DEFINES) -I/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/mkspecs/linux-g++ -I/home/uidq6356/workspace/practice/chess -I/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/5.5.1 -I/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/5.5.1/QtQuick -I/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/include -I/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick -I/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/include/QtGui -I/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/5.5.1 -I/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/5.5.1/QtQml -I/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/include/QtQml -I/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/include/QtNetwork -I/home/uidq6356/Tools/Qt5.5.1/5.5/gcc_64/include/QtCore square.h -o moc_square.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/QGuiApplication \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qguiapplication.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qglobal.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qconfig.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qlogging.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qflags.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmutex.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qstring.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qchar.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qobject.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qlist.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qiterator.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qregexp.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qisenum.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qeventloop.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qinputmethod.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qlocale.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qvariant.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmap.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qpair.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qdebug.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qhash.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qvector.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qpoint.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qset.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsize.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/QQmlApplicationEngine \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlapplicationengine.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlengine.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qurl.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qjsengine.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qjsvalue.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qtqmlglobal.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlerror.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmldebug.h \
		square.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/5.5.1/QtQuick/private/qquickrectangle_p.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/qquickitem.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/qtquickglobal.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqml.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlprivate.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlparserstatus.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmllist.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmetaobject.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlcomponent.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/QObject \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/QList \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qevent.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qregion.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qrect.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmargins.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qfile.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qfont.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qaccessible.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qcolor.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qrgb.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qbrush.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qmatrix.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpolygon.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qline.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qtransform.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpainterpath.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qimage.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpixelformat.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpixmap.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/5.5.1/QtQuick/private/qtquickglobal_p.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qloggingcategory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

square.o: square.cpp square.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/5.5.1/QtQuick/private/qquickrectangle_p.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/qquickitem.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/qtquickglobal.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qglobal.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qconfig.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qlogging.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qflags.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmutex.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqml.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlprivate.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qtqmlglobal.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qvariant.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qstring.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qchar.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qlist.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qiterator.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qregexp.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qisenum.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmap.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qpair.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qdebug.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qhash.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qobject.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qlocale.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qvector.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qpoint.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qset.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qurl.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlparserstatus.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmllist.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmetaobject.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlcomponent.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qqmlerror.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQml/qjsvalue.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/QObject \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/QList \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qevent.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qregion.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qrect.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qmargins.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsize.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qfile.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qfont.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qaccessible.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qeventloop.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qcolor.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qrgb.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qbrush.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qmatrix.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpolygon.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qline.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qtransform.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpainterpath.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qimage.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpixelformat.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtGui/qpixmap.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtQuick/5.5.1/QtQuick/private/qtquickglobal_p.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/qloggingcategory.h \
		../../../Tools/Qt5.5.1/5.5/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o square.o square.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_square.o: moc_square.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_square.o moc_square.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/qmlPractice/bin || mkdir -p $(INSTALL_ROOT)/opt/qmlPractice/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/qmlPractice/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/qmlPractice/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/qmlPractice/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

